name: 'ShellCheck'

on:
  pull_request:
    paths:
      - '**.sh'
      # this is too wide but will cover shell scripts without an extension in that folder
      - 'bin/*'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    env:
      SHELLCHECK_OPTS: -s bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          version: v0.9.0
          format: tty
